sudo: required

services:
  - docker

install:
  - docker build . -t alexpirine/sshtun

script:
  - echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/sshtun
